name: Lint
on:
  workflow_dispatch:
  push:
    tags:
      - v*
    branches: 
      main
      beta
  pull_request:
    branches:
      main
      beta

env:
  CACHE_KEY: 'hugo-hinode-template'

permissions:
  pull-requests: read
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v6

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: lts/*
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    # [24/AUG/23] Adjusted from npm ci to prevent EBADPLATFORM error due to fsevents
    - name: Install npm
      run: npm i

    - name: Lint the source files
      run: npm run lint
